### ISSUE TITLE
Code does not compile.

### ISSUE THREAD

**Issue by theboy6545** [judgex/desertrose#1085]
[Priority]: # high

[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) Try to compile the code from github, it does not work.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.) loading tgstation.dme
loading interface\skin.dmf
interactions\lewd\_lewd.dm:23:error: returnhas_penis: undefined var
interactions\lewd\_lewd.dm:26:error: returnhas_vagina: undefined var
interactions\lewd\_lewd.dm:29:error: returnhas_breasts: undefined var
interactions\lewd\lewd_species.dm:7:error: H.has_penis: undefined var
interactions\lewd\lewd_species.dm:10:error: H.has_vagina: undefined var
interactions\lewd\lewd_species.dm:16:error: H.has_breasts: undefined var
code\__HELPERS\_cit_helpers.dm:44:error: has_penis: duplicate definition
interactions\lewd\_lewd.dm:22:error: has_penis: previous definition
code\__HELPERS\_cit_helpers.dm:56:error: has_vagina: duplicate definition
interactions\lewd\_lewd.dm:25:error: has_vagina: previous definition
code\__HELPERS\_cit_helpers.dm:61:error: has_breasts: duplicate definition
interactions\lewd\_lewd.dm:28:error: has_breasts: previous definition
code\modules\mob\living\simple_animal\hostile\deathclaw\funclaw.dm:52:error: M.has_vulva: undefined proc
code\modules\mob\living\simple_animal\hostile\deathclaw\funclaw.dm:101:error: M.has_vulva: undefined proc
interactions\lewd\_lewd.dm:330:error: src.has_penis: undefined var
tgstation.dmb - 15 errors, 0 warnings (12/9/20 10:16 pm)

**Comment by judgex** [comment]
You must also pull in the submodule in the /interactions folder in order to compile.
