### ISSUE TITLE
Ballistics - Not Good

### ISSUE THREAD

**Issue by TheBananaBunch** [judgex/desertrose#24]
**= THE BULLETS MAN =**
So right now, from the looks of it there are only three ways of fighting that can get you any results. Those being;
An overpowered gun, a melee weapon or a bomb. 
If you are not using a Pancor, Assault Rifle, Energy Weapon or Fire axe - chances are anyone you fight that is using such a weapon, will cream you instantly without even trying. To me that is not particularly fair, it's quite punishing to those of us who roleplay and don't go around trying to kit out, especially when we spend the round building a settlement only to have everyone get killed by 1 or 2 guys. This I recommend, you remedy very much.

The reason being for things like the Assault Rifle and Sledgehammer, is that these weapons avoid an issue with ranged combat that a lot of people deal with, which is that projectiles are very slow. Incredibly slow, which having been discussed on the server I've yet to encounter any opposition towards this notion, it's actually such a problem that if you shoot at a person from a distance of 5+ tiles or less, it's really up to them whether or not whether they get shot.

I myself have seen to this, exchanged fire with a legionnaire and we shot maybe 20+ bullets in each other's direction, I think I was hit once in that whole firefight. Most of it was close range fighting too, it's just too damn easy to dodge bullets on DS. Same happens with most of my fights, if I got a bumper sword and someone is shooting at me with a revolver or a rifle, that person is just screwed.

Anyway, simple fix is you make bullets go faster and also subsequently lower the amount of damage that the Burst Fire weapons deal - since they already kill in a single burst. The Pancor Jackhammer also, I would say is extremely broken and it's been used to wipe out entire factions by many a solo player. 

It should also hopefully create a balance between energy and projectile weaponry, because the whole point of those in Fallout was that they shot slower and were less accurate in exchange for more damage. Which is not the case at all, energy weapons don't have a downside to them right now. It's kind of a weird pyramid of balance, where whoever is using the top tier gear is indestructible and anyone stuck with a hunting rifle or a revolver is just cannon fodder. 

**Once again** - reminder, if you make bullets go faster you need to nerf;
Pancor Jackhammer + ANY other burst fire weapon, just like Obsidian did. I remember modding New Vegas myself, if you look at the numbers they understood the same issue - automatic weapons in that game deal much less damage then their semi-automatic counterparts.

**Comment by judgex** [comment]
This is a really good, well thought out write-up.  We'll see if we can address this in part or altogether with upcoming code changes.  

Thank you for your effort and sharing your experience on the matter.  Input like this is valuable to us..

**Comment by TheBananaBunch** [comment]
To add on after some evening discussion with Vex.

Guns and Armor, having this weird tier system doesn't really make anything more fun.

I mean, why not just let anyone wear whatever armor or use any gun they like, not put them in a situation where they are wearing some cool tribal gear but know - it's complete garbage. They've got a nice hunting rifle, but the reality is the shotgun they just found is ten times better. If you guys want to make changes to any armor or guns in future, just consider making them or less balanced out.

**Comment by Jeff-Dome** [comment]
Git gud scrub, and thus why using TG isn't good for arrr pee you ding bong poo poo brains.

**Comment by TheBananaBunch** [comment]
Issue closed long time ago, I became a dev and did it myself.
