### ISSUE TITLE
Switch_gathering_mode icon doesn't appear plant bags when...

### ISSUE THREAD

**Issue by Laus4Deus** [judgex/desertrose#335]
[Priority]: # NULL

[Reproduction]: # Plant bags that are part of a load out or made with cloth don't show up the Switch_gathering_mode icon on the top left corner of the map. Plant bags that are in the map and taken from vendors work properly.

The item paths are all the same `/obj/item/storage/bag/plants` too.

The catch is that when dropped and picked back up, the bags now show the icon. I am unable to find *why* but that's the fix.

**If you ever get an ahelp saying "the plant bag is broken" tell the player to drop the bag and pick it back up. That will show the item**

**Comment by Trilbyspaceclone** [comment]
its do to how items are placed in peoples hands when crafting, iirc could be fucken wrong, it *spawns* it into their hand, but to get the action menu you have to pick up the item. This makes it not trigger the proc to give the command.
Again could be wrong
