### ISSUE TITLE
Port dark matter engine!

### ISSUE THREAD

**Issue by Laus4Deus** [judgex/desertrose#351]
It is the most fallout-ish from the ss13 fluff

**Comment by Trilbyspaceclone** [comment]
https://github.com/judgex/desertrose/tree/1ba207297f6d87258a50b73d8ea60c736d463ea3/code/modules/power/antimatter
This?

**Comment by Laus4Deus** [comment]
...
wait, and there is a .dmi with sprites....

**Comment by Laus4Deus** [comment]
Engine? Works.
Needs: Implementation
Needs: New sprites.
