### ISSUE TITLE
Zulius couldn't craft combat leather jacker.

### ISSUE THREAD

**Issue by Laus4Deus** [judgex/desertrose#370]
[Priority]: # medium. If this happens ofter? that's wack.

Direct quote: "Was unable to craft a combat leather jacket at a workbench despite having all of the materials for it (leather, gecko skin, brahmin skin, leather jacket)."

**Comment by goodolrusty** [comment]
Can't replicate this myself.  Perhaps a fluke?

**Comment by Laus4Deus** [comment]
It worked for me as well.
Maybe there are gecko skins spawned in the map and the item path is different to butchered geckos?
