### ISSUE TITLE
Brave Bull liquid vanishes when mixing.

### ISSUE THREAD

**Issue by redpepperphoenix** [judgex/desertrose#418]
[Priority]: # low

[Reproduction]: # 2 parts tequila and 1 part Kahlúa makes the regents vanish instead of making Brave Bull

**Comment by Laus4Deus** [comment]
`/datum/chemical_reaction/brave_bull
	name = "Brave Bull"
	id = "bravebull"
	results = list("bravebull" = 3)
	required_reagents = list("tequila" = 2, "kahlua" = 1)`
The recipe indeed exists but ahahha eheheh, the drink itself is not implemented.

**Comment by zuliouse** [comment]
oops

**Comment by FlickTee** [comment]
This seems to be added
