### ISSUE TITLE
Tile with questionable name in reachable location

### ISSUE THREAD

**Issue by Korozashisakae** [judgex/desertrose#433]
[Priority]: ???

Found the tile known as "What the fuck mappers? why is this here", was told by it to report this, it is located in the Pahrump map, behind a breakable rock wall in the structure with all the supermutants inside the sewer. Hope this wasn't a joke I didn't understand
attached image should (Hopefully?) show it.
![broken](https://user-images.githubusercontent.com/67039337/84857028-1ed1a600-b036-11ea-88a1-0d7d2d89567a.PNG)

**Comment by jjpark-kb** [comment]
we should close this as its intentional.
