### ISSUE TITLE
Spraypaint cans don't do anything.

### ISSUE THREAD

**Issue by ErikNielsen2014** [judgex/desertrose#438]
Issue reported from  Round ID: 1368 (Desert Rose 2)

Reporting client version: 512

Spray cans haven't worked for me in any capacity. They have not shown any graffiti, neither letters nor any images. Further they don't seem to change the color of objects. However attempting to use them in these tasks does reduce the number of uses of paint in the spraycan.

**Comment by Laus4Deus** [comment]
Please, see if you can repeat the bug and ask someone else to do it for you as well
