### ISSUE TITLE
Cant put beaker ( Large and smoll) on Grinder that has been built

### ISSUE THREAD

**Issue by BeatoWalker** [judgex/desertrose#440]
Issue reported from  Round ID: 1371 (Desert Rose 2)

Reporting client version: 513

Cant put beakers on a grinder that has been built as a vault dweller

**Comment by jjpark-kb** [comment]
I was unable to replicate this. Perhaps it was a bug but was fixed already?

**Comment by BeatoWalker** [comment]
if i remember correctly, it happen on vault area. when i print the grinder machine board and built the machinery, for some reason i cant put any beaker on it
