### ISSUE TITLE
Roles that are not well placed in the Manifest

### ISSUE THREAD

**Issue by Laus4Deus** [judgex/desertrose#442]
The roles that show in Miscellaneous are

should go in oasis:
Shopkeeper & Citizen (settler)
should go as follower
Practitioner
should go as wasteland
Outlaw
Detective
should go as tribal
villager, chief, shaman

**Comment by goodolrusty** [comment]
To fix this I BELIEVE we have to touch the jobs.dm file.

**Comment by nokele** [comment]
Was fixed, close.
