### ISSUE TITLE
A stove change into microwave

### ISSUE THREAD

**Issue by BeatoWalker** [judgex/desertrose#447]
[Priority]: # (Is it game breaking?)
Depend if you like to be baffled

[PR]: # (If you think you know the specific code / PR causing the problem then please do tell.)
Well i do know that the sprite originally from a microwave

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
If you clean up a stove in kitchen/ bar at oasis using a soap, it will change into microwave. it's not game breaking but change the RP and makes people baffled if you someone did that

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

[Notes]: # (Other notes.)

**Comment by goodolrusty** [comment]
This should be a simple fix to the icon_update part of the code.
