### ISSUE TITLE
Trays can be eaten

### ISSUE THREAD

**Issue by Merpkiller** [judgex/desertrose#509]
Issue reported from  Round ID: 1513 (Desert Rose 2)

Reporting client version: 513

I accidentally threw a tray full of potato wedges into the deep fryer, trying to eat off the fry batter actually ended up consuming the entire stack, and the tray itself. May be a bug that could affect other items.

**Comment by zuliouse** [comment]
doesn't this happen with practically anything that you fry?

**Comment by Laus4Deus** [comment]
Yes it does.
I want to do something about the fry. Maybe it only accepts food or smt

**Comment by FayetteFrost** [comment]
This is working as  intended.
