### ISSUE TITLE
Unable to set occupation preference of FoA members above NEVER

### ISSUE THREAD

**Issue by BotomQuark** [judgex/desertrose#619]
[Priority]: It's not game breaking, can reduce number of FoA players.

[PR]: No idea how that part of code works. Would need to jump into code to check that myself.

[Reproduction]: 
The bug is easy to spot. In "Join Game!" window there's an option to join as Follower of the Apocalipse member (pic below).
![Bez tytułu](https://user-images.githubusercontent.com/32230367/89210932-461e0b80-d5c1-11ea-9080-04953571c69d.png)
((that part I presume works since I can see one person playing as Partitioner))

The "Set Occupation" window looks for me like that:
![Bez tytułu](https://user-images.githubusercontent.com/32230367/89211147-a90fa280-d5c1-11ea-8aa1-3aad7e7490e2.png)

The problem is that the occupation for FoA faction is set to NEVER, and I cannot rise them ((both right click and left click doesn't work)). Every other occupation that is not locked, can be set to every single occupation preference level (low/medium/high).

Additionally, if any occupation is set to high, right-clicking any of the FoA occupation ((that would normally set it to high)) sets the original occupation to medium ((bcs there can be only one occupation set to high. The code executes the "onclick" command and sets the rest of "High" priorities to medium. When setting any occupation to high, and then right-clicking the FoA occupation, the original high priority changes to medium if done the second time, the same happens. What means the problem is not about the UI not changing "NEVER" to "High". It just never updates to High)).

[Notes]: 
Operating system: Windows 10
Byond Version: 513.1527
Server Status:
![Bez tytułu](https://user-images.githubusercontent.com/32230367/89212071-238cf200-d5c3-11ea-8f85-b0e68b678487.png)

**Comment by nokele** [comment]
Yep happens here too, will look into.
