### ISSUE TITLE
A really annoying bug

### ISSUE THREAD

**Issue by koonerr** [judgex/desertrose#681]
Issue reported from  Round ID: 1700 (Desert Rose 2)

Reporting client version: 513

So as I was playing on a server, CEV Eris, I got bored and quit, I then joined my favorite CM server, and a strange bug popped up, I can do anything with left click, it wont even point my character in the direction I clicked, I thought it was just with that server so I joined Fallout 13 and it didn't go away, It also popped up on CEV Eris after to.

**Comment by nokele** [comment]
Can't do anything about this, close it.
