### ISSUE TITLE
Flavor text requires proximity to examine

### ISSUE THREAD

**Issue by Celyne-git** [judgex/desertrose#77]
Priority: Low-Medium

> /mob/living/carbon/human/canUseTopic(atom/movable/M, be_close=FALSE, no_dextery=FALSE)
    if(incapacitated() || lying )
        to_chat(src, "<span class='warning'>You can't do that right now!</span>")
        return FALSE
    if(!Adjacent(M) && (M.loc != src))
        if((be_close == 0) || (dna.check_mutation(TK) && tkMaxRangeCheck(src, M)))
            return TRUE
        to_chat(src, "<span class='warning'>You are too far away!</span>") //Bug: this is preventing flavor text from being seen except when adjacent. See print_flavor_text() in preferences.dm
		return FALSE
	return TRUE

In mob/living/carbon/human/human.dm: his is preventing flavor text from being seen except when adjacent. See print_flavor_text() in code/modules/client/preferences.dm. 
(Confirmed- if you have TK, you can read flavor text at range.)
I don't know href stuff well enough to fix this one. Short version? You can't read people's in-depth flavor text (past 40 characters) except when adjacent because of it calling canUseTopic() when you attempt to open the ref.

**Comment by judgex** [comment]
This issue was resolved by update #113
