### ISSUE TITLE
Runtime in generic_negative_events.dm

### ISSUE THREAD

**Issue by goodolrusty** [judgex/desertrose#807]
[23:30:20] Runtime in generic_negative_events.dm, line 137: undefined variable /datum/component/mood/var/faction_

proc name: add effects (/datum/mood_event/saw_many_unburied_faction/add_effects)
usr: [[Redacted for privacy as it has ckey info]] (/mob/living/carbon/human)
usr.loc: road (232,115,2) (/turf/open/indestructible/ground/outside/road)

usr: [[Redacted for privacy as it has ckey info]] (/mob/living/carbon/human)
usr.loc: sidewalk (186,179,2) (/turf/open/indestructible/ground/outside/sidewalk)

**Comment by MarinaGryphon** [comment]
Fixed in #826
